// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGame(arg1:number):Promise<void>;

export function DeleteSteamCache():Promise<string>;

export function GetInstalledGames():Promise<Array<main.Game>>;

export function GetSteamDir():Promise<string>;

export function InstallDll():Promise<void>;

export function IsDllInstalled():Promise<boolean>;

export function RemoveDll():Promise<void>;

export function RemoveGame(arg1:number):Promise<void>;

export function RestartSteam():Promise<string>;

export function SearchGames(arg1:string):Promise<Array<main.Game>>;

export function SelectSteamDir():Promise<string>;
