// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1) {
  return window['go']['main']['App']['AddGame'](arg1);
}

export function DeleteSteamCache() {
  return window['go']['main']['App']['DeleteSteamCache']();
}

export function GetInstalledGames() {
  return window['go']['main']['App']['GetInstalledGames']();
}

export function GetSteamDir() {
  return window['go']['main']['App']['GetSteamDir']();
}

export function InstallDll() {
  return window['go']['main']['App']['InstallDll']();
}

export function IsDllInstalled() {
  return window['go']['main']['App']['IsDllInstalled']();
}

export function RemoveDll() {
  return window['go']['main']['App']['RemoveDll']();
}

export function RemoveGame(arg1) {
  return window['go']['main']['App']['RemoveGame'](arg1);
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SelectSteamDir() {
  return window['go']['main']['App']['SelectSteamDir']();
}
